### ISSUE TITLE
Exploring unsupported use cases

### ISSUE THREAD

**Issue by jonjamz** [okgrow/iron-router-autoscroll#1]
Would it be correct to say that the biggest unsupported case for this is where subscriptions aren't waited upon by Iron Router?

**Comment by pauldowman** [comment]
Yes. I haven't explored it at all yet, but that seems to be the main one. 

Another issue is that the way I keep track of state for the back button is not that elegant (and doesn't allow for multiple entries per URL), I think it should be possible to store the position as state right on the history object.
