### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by dalgard** [okgrow/iron-router-autoscroll#10]
I have a rather standard application with a document list linking to document pages. When clicking a link in the list, the document page does not get scrolled to top. And when going back, the list is not scrolled to the previous position.

Please make a big note about this package being out of order, if it is so...

P.S. Sorry for the useless title, but the package simply doesn't seem to work. Thanks.

**Comment by pauldowman** [comment]
It definitely works, but see the note in the README about the iron router bug after a hot code push (which now has an open PR so should be fixed soon). 

Try  manually reloading the page. Also check your console for errors.

Let me know if that doesn't help.

**Comment by dalgard** [comment]
Neither scroll-to-top nor restore position seems to work, with no errors in the console.

I saw the note – also saw the note about dynamic content, so I have to admit I would have expected the package to be deprecated if not for the recent commits, seeing as I wouldn't expect the feature to be an easy one to pull off. Thanks again.

**Comment by pauldowman** [comment]
But can you confirm that it works if there has been no hot code push? Manually refresh the page.

I don't understand the second paragraph of your last comment, can you explain? What note about dynamic content? And why would it be deprecated?

**Comment by pauldowman** [comment]
@dalgard I'm closing this because I think it's #9 but feel free to re-open if it's not that. And I'll do my best to help you get it working if it's a conflict with something else.
