### ISSUE TITLE
Possible to support modals?

### ISSUE THREAD

**Issue by dcworldwide** [okgrow/iron-router-autoscroll#11]
I've tested the code with remodal and leanmodal. In your opinion could the code be extended to support scrolling to content within a modal?

E.g. IR runs route /:id/:itemId#subItemId. The route triggers a modal to display ItemId. I want to then scroll the modal to subItemId. 

The flow i've tested is:
- IR runs route /:id/:itemId#subItemId. In this case, the modal div is pre-rendered in the page. When the route.action() callback runs, it uses jquery to translate the div into a modal and open the modal window 
- Modal opens
- As the modal div was pre-rendered, the Window scrolls to the location of #subItemId on the page, but not within the popup.

**Comment by deanrad** [comment]
This issue was moved to okgrow/router-autoscroll#10

**Comment by deanius** [comment]
In order to support this, please start a PR, and make an example of your situation in either or both router examples in the `examples/` directory. This way we can both be looking at the same example.
