### ISSUE TITLE
Scroll-to-top broken with Iron Router and appcache

### ISSUE THREAD

**Issue by dkmooers** [okgrow/iron-router-autoscroll#13]
Appcache hashifies Iron Router routes:

`/settings`

becomes

`/#!settings`

And that breaks autoscroll-to-top when we try to do this:

`var hash = window.location.hash;`

`} else if ($(hash).length) {`

Doing `$('#!settings')` throws the error.

So we should strip out any appcache hashified routes with regex I think, i.e. anything with `#!` in it should not be part of the hash.

**Comment by dkmooers** [comment]
Here's a solution that I think would work.

Instead of `hash`:

```
var anchor = window.location.hash.replace(/^.*(#.*?)$/, '$1');
if (anchor && $(anchor).length) {
    position = $(anchor).offset().top;
}
```

EDIT: regex typo.

If your URL was:

`#!settings#anchor`

It would grab `#anchor` off the end and use that to calculate position.

**Comment by pauldowman** [comment]
@dkmooers I'm sorry but I don't understand the issue. Can you explain? Do you mean that the appcache packages changes your routes somehow? It's been a while since I've used it but I don't recall that.

Or do you mean that you use hash-based URLs to avoid having certain things cached?

Or do you mean that when using #! URLs it doesn't work to also have an anchor tag? I think this is what you mean.

I'm assuming it's not valid to have both a hash-based url and an anchor tag. Admittedly I haven't spent much time thinking about this so let me know if I'm confused, but I don't think that would work with or without this package, I'm not sure if we can can do anything here.

**Comment by dkmooers** [comment]
Both 1 and 3. Yeah, so appcache actually changes the URLs of the routes. Kind of bizarre, not sure why it does that.

Without appcache:

`www.foo.com/bar#anchor`

With appcache:

`www.foo.com/#!bar#anchor`

Which breaks the scrolling-to-anchor by autoscroll, since it includes the "#!" url in the hash/anchor. Hence the regex suggestion to make it actually grab ONLY the anchor from the hash, instead of also grabbing hashed URLs.

I ended up just making my own implementation, which is simpler, since I've decided I don't actually want the scroll position to return to previous when you hit the back button, so I'm just using this implementation in my global onBeforeAction, which scrolls to anchors properly (even given hashed URLs):

```
var position = 0;
var anchor = window.location.hash.replace(/^(.*)(#.*?)$/, '$1');
if (anchor && $(anchor).length) {
    position = $(anchor).offset().top;
}
$('body,html').animate({
    scrollTop: position
}, 0);
```

Does that make sense?

**Comment by dkmooers** [comment]
I'm not using appcache anymore, because of a few other problems it created, but just thought I'd throw this in there. If nobody else needs it, may not be worth the fix.

**Comment by deanrad** [comment]
This issue was moved to okgrow/router-autoscroll#8

**Comment by deanrad** [comment]
@dkmooers - in the new repo, a fix for oddball hashbang urls is in place, could you check it out and update the ticket there when you can please ?

**Comment by dkmooers** [comment]
Just looked at the code and didn't see a change for this. Looks like maybe not doing for now?

https://github.com/okgrow/router-autoscroll/issues/8#issuecomment-140816301

Don't have time to test anything ATM, been on vacation and came back to a rash of non-Meteor projects.
