### ISSUE TITLE
Scroll to top not working

### ISSUE THREAD

**Issue by niranjans** [okgrow/iron-router-autoscroll#14]
Is there any configuration that is required with Iron Router while adding this package? Iron router does not scroll to top when loading a new page. However, this is still true even after I added this package so I'm wondering if I'm doing something wrong.

**Comment by niranjans** [comment]
I figured it out. I have a wrapper div around my content which is set to overflow scroll and not the html / body tag.

**Comment by pauldowman** [comment]
Excellent, glad it's working for you!
