### ISSUE TITLE
Mobile browser support?

### ISSUE THREAD

**Issue by phocks** [okgrow/iron-router-autoscroll#15]
For some reason this wasn't scrolling to the top for me when I tested on Chrome and Safari on iOS 8. I would click on a link that was down the page a bit and it would load half scrolled down. Seemed to work perfectly on Desktop. Strangely when I pressed the back button on Mobile I still got the animation though to where I left off.

I managed to achieve similar functionality with:

```
Router.onBeforeAction(function() {  
  $(window).scrollTop(0);
  this.next();  
});
```

Of course this doesn't have the animation scroll, but I don't really need that.

Has anyone else got this package working on Mobile browsers?

**Comment by pauldowman** [comment]
Thanks for reporting it, we'll check this out. In the meantime you might want to double-check that it's not #9.

**Comment by phocks** [comment]
Thanks, no I have tried refreshing manually. I should be able to look in to the code more when I have a bit more time next week.

**Comment by deanrad** [comment]
This issue was moved to okgrow/router-autoscroll#7
