### ISSUE TITLE
Autoscroll scrolls back to top even when only query parameters are changing

### ISSUE THREAD

**Issue by SachaG** [okgrow/iron-router-autoscroll#16]
I'm not sure if this is the intended behavior, but the package scrolls back to the top of the page even when only a query parameter is changing (i.e. going from `/posts/?count=10` to `/posts/?count=20`).

Seems to me like this would conflict with a lot of pagination/filtering implementations? Shouldn't the autoscroll only happen when the route itself changes?

**Comment by pauldowman** [comment]
Yeah, this has come up before. The trouble is that changing the query string often is navigation to another page, e.g. search results where you have `?page=2` (or `?start=10` as Google does).

It could definitely be an option though. I'll take a look at this, or if anyone submits a PR before I get to it I would be much appreciated too. :stuck_out_tongue_winking_eye:

**Comment by SachaG** [comment]
That's true. Maybe then autoscroll could be deactivated on a per-route basis, as long as you stay inside the same route?

**Comment by deanrad** [comment]
A new flag was just added, which you can call when you're updating the querystring and don't want scroll changes. That should work?

```
Router.go('newRoute', {}, {
  query: {q: 'newQuery'},
  hash: 'maintainScroll=1'
});
```

**Comment by SachaG** [comment]
Ooh, can't wait to test this :)

**Comment by phocks** [comment]
Great feature. This looks really good. I wonder if it would work with directory structures like `/page/2` changing to `/page/3`. Could possibly be made to work similarly I imagine.

**Comment by deanrad** [comment]
@phocks - If you have an idea, I'd check out a PR.. But I'm closing this issue now as we're moving issues over to the new repo: https://github.com/okgrow/router-autoscroll
