### ISSUE TITLE
Scroll triggers late

### ISSUE THREAD

**Issue by SachaG** [okgrow/iron-router-autoscroll#17]
I've noticed that on some occasions, the scroll triggers a few moments too late, which means the user has already started scrolling down the page and is forcibly brought back to the top. 

Maybe the package could listen for the scroll event, and not trigger if the user has already started scrolling?

**Comment by pauldowman** [comment]
Great suggestion, we should definitely do that. I'll try to find time for it soon.

**Comment by deanrad** [comment]
This issue was moved to okgrow/router-autoscroll#6
