### ISSUE TITLE
Doesn't work with position absolute

### ISSUE THREAD

**Issue by v3rron** [okgrow/iron-router-autoscroll#22]
I'm working on a mobile app and in order to have smoother scrolling my content div is positioned absolutely between header and footer. Looking at the code I can say that it uses $(window) element to scroll to the top of the page. Could you please add support for custom div wrapper element to be passed as main scrolling div?
Currently my layout looks like this:

```
<template name="ApplicationLayout">
  {{> yield "header"}}
  {{> connectionBanner }}
  {{> _updateNotification }}
  {{> _flashMessages }}
  {{> yield "sidebar" }}
  <div class="pusher">
    <div id="wrapper">
      <div id="content">
        <div class="absolutely">
          {{> yield }}
        </div>
      </div>
    </div>
  </div>
  {{> yield "footer"}}
</template>
```

The issue with this layout is that body and wrapper elements css have `position: absolute; overflow: hidden;` and are not scrollable, the only scrollable div here is `<div class="absolutely">{{> yield}}</div>`. So `$(window).scrollTop()` won't work in this case.

**Comment by deanrad** [comment]
This issue was moved to okgrow/router-autoscroll#4
