### ISSUE TITLE
new ScrollRestoration API

### ISSUE THREAD

**Issue by nicolasparada** [okgrow/iron-router-autoscroll#23]
There is a new history.scrollRestoration API:
[https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration) --[Specs here](http://majido.github.io/scroll-restoration-proposal/history-based-api.html)
Check it :)

**Comment by deanrad** [comment]
Migrated issue to https://github.com/okgrow/router-autoscroll/issues/3
