### ISSUE TITLE
Jump to top on form submit

### ISSUE THREAD

**Issue by jakobloekke** [okgrow/iron-router-autoscroll#3]
I'm experiencing that form submissions cause a scroll to the top.
Have anyone else seen this happen?

**Comment by pauldowman** [comment]
@jakobloekke Thanks, I'll investigate.

**Comment by rgould** [comment]
@jakobloekke I'm having trouble replicating this. With a simple dummy app and a simple form, I don't find that the autoscroller is kicking in. How is the form being submitted? How are you handling the submit event? If `event.preventDefault()` is not called, that will trigger a refresh, which would cause it to reload at the top of the page.

**Comment by pauldowman** [comment]
@jakobloekke I'm closing this for now, but let us know if you can reproduce it.
