### ISSUE TITLE
Change animation time hook

### ISSUE THREAD

**Issue by dkmooers** [okgrow/iron-router-autoscroll#4]
Any chance of making a hook so I can change the animation time? I'd like to do an instant scroll for the particular app I'm developing and it would be nice to do this without modifying the package.

**Comment by pauldowman** [comment]
I would be happy to take a pull request for that! :smile:

**Comment by dkmooers** [comment]
It ended up being the perfect animation time, actually, but if I need to
change it I will definitely make a pull request!

Cheers,
Devin

**Comment by pauldowman** [comment]
OK! Well I'll close it for now until someone else wants to tweak the animation time.
