### ISSUE TITLE
Doesn't work after hot code push due to Iron Router bug

### ISSUE THREAD

**Issue by pauldowman** [okgrow/iron-router-autoscroll#9]
This is caused by https://github.com/iron-meteor/iron-router/issues/1219 and doesn't happen very often in production but it's very confusing in development. We should fix the issue in Iron Router.

**Comment by deanrad** [comment]
We've added a data structure to remember scroll positions across a hot code push, and maybe this will allow for us to hook the hot code push itself ? https://forums.meteor.com/t/is-there-a-hot-code-push-live-reload-hook/7028

**Comment by deanrad** [comment]
We now restore scroll position after a hot code push. 

It's not so much a router bug, but the fact that hot code push calls `window.location.reload()` (but the router not handling this doesn't help)
https://github.com/okgrow/router-autoscroll/commit/e4dcec1001ea84f00a6db5444f6652517bd62fd0
